version: 2.6.2
HuLa-IM:
  HOST: 127.0.0.1 #域名
  MYSQL_PORT: 3306 #端口
  DATABASE_NAME: hula-im #数据库名
  MYSQL_USER_NAME: root #数据库用户名
  MYSQL_PASSWORD: 123456 #数据库密码
  REDIS:
    PAW: 123456 #redis密码, 如果是数字密码最好用引号包裹起来
    PORT: 6379 # redis端口号
  WX: # 微信配置
    CALLBACK: https://468ov9ww8878.vicp.fun
    APPID: wxb28a0fd6d1cae6ba
    SECRET: 9c215f8d078422805218221144b9095b
    TOKEN: nongyehong
    AESKEY: 7iNecFLZ8nbtCaMntHYEruSHP1Mk8FmGvrkHwnJzwug
  JWT: #JWT配置
    SECRET: dsfsdfsdfsdfsd
  ROCKETMQ: #rocketmq配置
    NAME-SERVER: 127.0.0.1:9876  # 修改为与broker.conf一致
    ACCESS-KEY: nongyehong
    SECRET-KEY: 919919919
  mail:
    username: nongyehong919@163.com  # 发件人邮箱
    password: ZDiFAsKBBJSZVBBR    # 邮箱SMTP授权码

uid:
  database:
    # 时间位分配（默认41）
    time-bits: 41
    # 工作节点位分配（默认13）
    worker-bits: 13
    # 序列号位分配（默认9）
    seq-bits: 9
    # 起始时间
    epoch-str: "2025-02-25"
    # 随机序列上限（默认0，表示不启用随机）
    random-sequence-limit: 0
    # 分页最大数量
    max-limit: 500
    # 防止全表更新与删除插件
    is-blockAttack: true
    # 溢出总页数后是否进行处理
    overflow: true